version: '3.1'

services: 
  db:

    image: postgres:12.1

    environment: 
      - POSTGRES_USER=uh
      - POSTGRES_PASSWORD=hi

    volumes:
      - db-data:/var/lib/postgresql/data
    
    networks: 
      - wp

  web:
    build: .

    image: custom-drupal
    
    ports: 
     - 8080:80

    networks:
      - wp

    volumes:
      - site-modules:/var/www/html/modules
      - site-profiles:/var/www/html/profiles
      - site-sites:/var/www/html/sites
      - site-themes:/var/www/html/themes

volumes:
  db-data:
  site-modules:
  site-profiles:
  site-sites:
  site-themes:  

          
networks: 
  wp:
